name: "AWS Configure"
inputs:
  aws-region:
    required: true
    description: "The AWS region used to authenticate with AWS"
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: Stackla/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::953585160895:role/GitHubAction-AssumeRoleWithAction
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true