name: E2E
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches:
      - master
env:
    NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}

jobs:
    associate-release:
        runs-on: ubuntu-latest
        steps:
            -   name: Logs
                run: |
                    echo "Release identifier: ${{ github.event.inputs.release_identifier }}"
            -   name: Write inputs to file
                if: github.event.inputs.release_identifier != ''
                run: |
                    echo "${{ github.event.inputs.release_identifier }}" > release.txt

            -   name: Upload release identifier
                uses: actions/upload-artifact@v4
                if: github.event.inputs.release_identifier != ''
                with:
                    name: release
                    path: release.txt
    e2e:
        runs-on: ubuntu-latest
        environment: staging
        defaults:
            run:
                shell: bash
                working-directory: ./vendor
        strategy:
            fail-fast: false
            matrix:
                containers: [ 1, 2, 3 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                
            -   name: Cache cypress binary
                id: cypress-cache
                uses: actions/cache@v4
                with:
                    path: '~/.cache/Cypress'
                    key: ${{ runner.OS }}-cypress-cache-${{ hashFiles('pnpm-lock.yaml') }}
            -   name: Install cypress
                run: npx cypress install
            -   name: Cypress run e2e tests
                uses: cypress-io/github-action@v5
                env:
                    SPLIT: ${{ strategy.job-total }}
                    SPLIT_INDEX: ${{ strategy.job-index }}
                    DEBUG: cypress-split
                with:
                    browser: chrome
                    install: false
