name: CI

permissions:
  contents: write
  packages: read
  actions: write
  id-token: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install

  build:
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: Stackla/stackla-github-actions/npm-cache@master
      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: install
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
    steps:
      - uses: Stackla/stackla-github-actions/npm-cache@master
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
    steps:
      - uses: Stackla/stackla-github-actions/npm-cache@master
      - name: Test
        run: npm test