name: CI

permissions:
  contents: write
  packages: read
  actions: write
  id-token: write

env:
  GH_TOKEN: ${{ github.token }}
  NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Test
        run: npm test

  e2e:
    uses: ./.github/workflows/e2e.yml

  trigger_deploy:
    if: github.ref == 'refs/heads/master'
    needs: [build, e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: trigger deploy
        run: gh workflow run release --ref master -F environment=staging
