name: Release

run-name: Release to ${{ inputs.environment || 'staging' }} by @${{ github.actor }}

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  id-token: write
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run deployment in"
        type: environment
        required: true
        default: staging

jobs:
  e2e:
    uses: ./.github/workflows/e2e.yml

  deploy:
    needs: [e2e]
    environment: ${{ inputs.environment }}
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
      ENV_VARS: ${inputs.env_vars}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build widget-utils
        run: npm run build:utils
      - uses: ./.github/workflows/aws
        with:
          aws-region: ${{ vars.AWS_REGION }}
      - name: Build for environment
        env:
          APP_ENV: ${{ inputs.environment }}
        run: npm run build:${{ inputs.environment }}
      - name: Release to S3
        shell: bash
        run: |
          aws s3 sync dist/ s3://ugc-nextgen-widgets-ap-southeast-2/templates/${{ inputs.environment }}/widgets/
      - name: Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "stackla"
          SENTRY_PROJECT: ${{ github.event.repository.name }}
        with:
          environment: ${{ inputs.environment }}
          version: ${{ github.sha }}
          ignore_empty: true
