name: Release

run-name: Release to ${{ inputs.environment || 'staging' }} by @${{ github.actor }}

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  id-token: write
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run deployment in"
        type: environment
        required: true
        default: staging

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    env:
      NODE_AUTH_TOKEN: ${{secrets.STACKLA_BOT_GITHUB_TOKEN}}
      ENV_VARS: ${inputs.env_vars}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/workflows/serverless
        with:
          aws-region: ${{ vars.AWS_REGION }}
          stage: ${{ inputs.environment }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
